additional functions for vm-replicate

diff --git a/vm-replicate b/vm-replicate
--- a/vm-replicate
+++ b/vm-replicate
@@ -1,33 +1,27 @@
 #!/bin/bash
 
-cat << schedule
+: << schedule
 
 Similar to virtnbdrestore-auto (interactive) but creates a new VM based on definitions from an existing VM
 
 Lists all available VMs to choose one:
 
 Asks for:
-    New VM name (mandatory)
-    RAM (optional)
-    CPUs (optional)
-    For each interface:
-        MAC address: Randomize, keep, or insert custom (optional)
-        Network to be connected (optional)
-    if existing VM is not patched for incremental backups:
-        asks for patching
+    DONE New VM name (mandatory)
+    Patch for incremental backup (if not detected)
 
 Generate:
-    UUID
-    MAC addr (if NOT set to keep or was manually added)
+    DONE UUID
+    DONE MAC addr (per each interface)
 
 Modify:
-    disk images paths (based on VM name)
-    nvram image path (based on UUID)
+    DONE disk images paths (based on VM name)
+    DONE nvram image path (based on UUID)
 
 Copy/clone:
-    If source VM is running, shuts it down prior to perform a disk copy
+    DONE nvram (from qemu template) on given location
+    DONE If source VM is running, shuts it down prior to perform a disk copy
     writable disk images from original to new location (qemu-img)
-    nvram (from qemu template)
 
 Patch (if required by user)
 
@@ -37,104 +31,17 @@ Define the VM.
 schedule
 
 # Temporal path to store files (as .xml):
-working_path="/tmp"
+working_path="$HOME/.$(basename $0).tmp"
 
-# Base MAC address used on the qemu/kvm implementation:
-base_mac_addr="52:54:00"
-
-# Returns a string value with the state reported by libvirt (e.g. "running", "shut off", etc.)
-# -----------------------------------------------------------------------------
-domain_state()
-{
-    echo $(virsh domstate $1)
-}
-
-# For a given VM name, returns a string value with absoulte path to its image disks (e.g. "/path-to/hdc.img /path-to/hdd.img")
-# -----------------------------------------------------------------------------
-list_vm_img_paths()
-{
-    echo $(virsh domblklist --details $1 | grep -e file | grep -e disk | sed -e 's/ file //g' -e 's/ disk //g' | rev | cut -d' ' -f1 | rev )
-}
-
-# Sorts unordered items lexicographically. This is used for user input not in order:
-# -----------------------------------------------------------------------------
-sort_items()
-{
-    echo $@ | xargs -n1 | sort | xargs
-}
-
-# Sends shutdown signal and awaits until domain has been shutted down to return success:
-# -----------------------------------------------------------------------------
-shutdown_vm()
-{
-local shutdown_vm_status=1
-local vm_needed_state="shut off"
-
-if [[ $(domain_state $1) == $vm_needed_state ]]; then
-
-    echo "INFO: VM '$1' is already $vm_needed_state"
-    shutdown_vm_status=0
-else
-
-    local wait_time=15
-    local max_attempts=10
-    local attempt=1
-
-    while (( $attempt < $max_attempts )); do
-
-        virsh shutdown $1
-
-        sleep $wait_time
-
-        [[ $(domain_state $1) == $vm_needed_state ]] && { shutdown_vm_status=0; break; } || ((attempt++))
-    done
-
-    local message=""
-    [[ $shutdown_vm_status -eq 0 ]] && message="INFO: VM '$1' powered off successfully" || message="WARNING: Gave up after $(( $wait_time * $max_attempts )) secs. waiting for VM '$1' to power off"
-fi
-
-    echo $message
-    return $shutdown_vm_status
-}
-
-# Determines if a domain is patched for incremental backups, returning '0' if true, or '1' if false
-# -----------------------------------------------------------------------------
-vm_is_patched()
-{
-
-    local vm_is_patched_state=1
-
-    # Expected match on non-patched VMs:
-    local original_pattern="<domain type='kvm'>"
-
-    # Expected match on manually modified VMs (e.g. with 'virsh edit $target_domain')
-    local modified_pattern="<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>"
-
-    local match=$(virsh dumpxml --inactive --security-info $1 | grep -e "$original_pattern" -e "$modified_pattern")
-
-    [ $match == $modified_pattern ] && vm_is_patched_state=0
-
-    return $vm_is_patched_state
-
-}
-
-# Returns a random, uppercase,  MAC address, based upon (optional) base pattern 'XX:XX:XX'
-# -----------------------------------------------------------------------------
-gen_random_mac()
-{
-    local seed
-
-    # If no base pattern is provided, will use global parameter:
-    [[ -z $1 ]] && seed=$base_mac_addr
-
-    printf '%s:%02X:%02X:%02X\n' ${seed^^} $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256))
-}
+# Location of script where all functions and global variables to be used are declared:
+# (Here, on the same dir
+functions_path="$(dirname $0)/functions"
 
 # Main execution:
 # -----------------------------------------------------------------------------
 
-# Load all functions
-#source $PWD/functions.sh
+# Load functions:
+source $functions_path
 
 status=1
 if [ -z $@ ]; then
@@ -143,8 +50,8 @@ if [ -z $@ ]; then
     #show_help
     #read -n1 -s -r -p $'Press any key to continue, or Ctrl+C to Cancel...\n' key
 
-# Step 1: Asks the user to choose a VM to clone:
-# -----------------------------------------------------------------------------
+    # Asks the user to choose a VM to clone:
+    # -----------------------------------------------------------------------------
     vms_list=($(virsh list --all --persistent --name))
     if [ $? == 0 ] && [[ ${#vms_list[@]} -ge 1 ]]; then
 
@@ -171,60 +78,254 @@ if [ -z $@ ]; then
 
             if [[ $choice -ge 1 ]] && [[ $choice -le ${#vms_list[@]} ]]; then
 
-                source_vm="${vms_list[(( $choice - 1 ))]}"
-
-                # NOTE: expand this list with: CPU, RAM, drives, nets and macs
-                # Saves VM specs that will be used for restoration:
-                #vm_img_paths_list=($(list_vm_img_paths $source_vm))
-                #vm_patch_list+=($(vm_is_patched $source_vm))
-                #source_vm_state=(${vm_states_list[(( $choice - 1 ))]})
-
+                # If choice is consistent, saves the value and breaks the loop:
+                src_vm="${vms_list[(( $choice - 1 ))]}"
                 break
             else
+
+                # Otherwise, alerts about the error and asks for $choice again:
                 read -p "'$choice' is invalid. Please choose a number of the list [1-${#vms_list[@]}]: " choice
             fi
         done
 
         echo ""
-        echo "Virtual Machine '$vm_name' selected for being cloned"
+        echo "INFO: VM '$src_vm' selected for being replicated"
         echo ""
 
-# Step 2: Asks the user for New VM parameters:
-# -----------------------------------------------------------------------------
-        read -p "Insert the name of the virtual machine to be replicated from $source_vm': " vm_name
+        # Asks the user for a name to be used for the New VM:
+        # -----------------------------------------------------------------------------
+        read -p "Choose a unique name for the new VM to be replicated from $src_vm': " dest_vm
 
         while true; do
 
-            # Unlike $vms_list, transient VMs are scanned too:
-            for vm in "$(virsh list --all --name)"; do
-                # Checks if $vm_name is already defined:
-                [ $vm_name == $vm ] { matches_existing_vm=1; break; }
+            for vm in "${vms_list[@]}"; do
+
+                # Checks if $dest_vm is already defined, breaking the loop if so:
+                [ $dest_vm == $vm ] && { matches_existing_vm=1; break; }
             done
 
-                if [[ ! $matches_existing_vm ]]; then
-
-                    break
-                else
-
-                    read -p "'$vm_name' already exists. Insert a different name for the virtual machine to be replicated from $source_vm': " vm_name
-                fi
+            # End the loop if $dest_vm doesn't exist already, warns and asks for another name if it does:
+            [[ ! $matches_existing_vm ]] && break || read -p "'$dest_vm' is an existing VM. You must choose a different name for the new VM to be replicated from '$src_vm': " dest_vm
         done
 
-# Step 3: Dump $source_vm definitions and apply changes::
+        # Asks the user if copy disks from $src_vm for $dest_vm:
+        # -----------------------------------------------------------------------------
+        read -p "Do you want to copy disk images from '$src_vm' into '$dest_vm'? (NOTE: If '$src_vm' is running, it will be temporarily shutted down prior to perform the copy)' [yes/no]: " choice
+
+        while true; do
+
+            case $choice in
+
+                yes|YES)
+                    copy_disks=1
+                    break
+                ;;
+                no|NO)
+                    break
+                ;;
+                *)
+                    read -p "Please, write 'yes' or 'no': " choice
+                ;;
+            esac
+        done
+
+        # If incremental backup patch is not detected in $src_vm, asks the user for applying this patch into $dest_vm:
+        # -----------------------------------------------------------------------------
+        if [[ $(vm_is_patched $src_vm) == false ]]; then
+
+            # $src_vm isn't patched. Asks if $dest_vm should be patched:
+            read -p "Do you want to patch VM '$dest_vm' in order to accept incremental backups? [yes/no]: " choice
+
+            while true; do
+
+                case $choice in
+
+                    yes|YES)
+                        patch_vm=1
+                        break
+                    ;;
+                    no|NO)
+                        break
+                    ;;
+                    *)
+                        read -p "Please, write 'yes' or 'no': " choice
+                    ;;
+                esac
+            done
+        fi
+
+        echo ""
+        echo "INFO: Processing parameters for VM '$dest_vm'..."
+        echo ""
+
+        # Dumps $src_vm definitions apart, and apply changes:
+        # -----------------------------------------------------------------------------
+
+        # Create the temporary folder to be used:
+        mkdir -p $working_path
+
+        # Path to xml definitions file to be processed:
+        vm_definitions_file=$working_path/$dest_vm.xml
+
+        # Dumps current VMs XML file to a temporal location:
+        virsh dumpxml --inactive --security-info $src_vm > $vm_definitions_file
+
+        # Replaces $src_vm by $dest_vm:
+        # -----------------------------------------------------------------------------
+        sed -i -e "s|<name>$src_vm</name>|<name>$dest_vm</name>|" $vm_definitions_file
+
+        # Replaces UUID:
+        # -----------------------------------------------------------------------------
+
+        # UUID of $src_vm:
+        src_uuid=$(domain_id $src_vm)
+
+        # Random UUID to replace the original one:
+        dest_uuid=$(uuidgen)
+
+        # Replaces all matches of $src_uuid for $dest_uuid:
+        sed -i -e "s|$src_uuid|$dest_uuid|g" $vm_definitions_file
+
+        if [[ $(is_unraid) ]]; then
+
+            # On UnRaid, checks for nvram (already replaced with $dest_uuid, if exists):
+            vm_nvram_path=$(grep -e "<nvram>" $vm_definitions_file | cut -d'>' -f2 | cut -d '<' -f1)
+
+            if [ ! -z $vm_nvram_path ]; then
+
+                # If exists in definitions and not as file, a new nvram file must be provisioned.
+                # On UnRaid, it's located at a well defined path:
+                template_nvram_path="/usr/share/qemu/ovmf-x64/OVMF_VARS-pure-efi.fd"
+
+                # So, simply copies the template, renamed as the nvram filedefined for $dest_vm:
+                cp -f $template_nvram_path $vm_nvram_path
+
+                [[ $? -eq 0 ]] && echo "INFO: NVRAM device '$vm_nvram_path' successfully created." || echo "WARNING: Could not create a NVRAM device. Check the log above to detemrine the cause of the issue "
+            fi
+        fi
+
+        # Replaces MAC addresses for (qemu/kvm) random ones:
+        # -----------------------------------------------------------------------------
+
+        # Gets the original list of MAC addresses from $src_vm:
+        src_macaddr_list=($(get_vm_macaddr $src_vm))
+
+        for mac in ${vm_mac_addr_list[@]}; do
+
+            # Creates a random MAC addr for the given $src_vm MAC
+            dest_macaddr_list+=($(gen_random_macaddr))
+
+            # Replaces matching listed mac for a random one:
+            sed -i -e "s|<mac address='$mac'/>|<mac address='${dest_macaddr_list[${#dest_macaddr_list[@]}]}'/>|" $vm_definitions_file
+        done
+
+        # Replaces disk image names and/or paths
+        # -----------------------------------------------------------------------------
+
+        # Gets the original disk image paths of #src_vm:
+        src_img_paths_list=($(list_vm_img_paths $src_vm))
+
+        i=0
+        for path in ${src_img_paths_list[@]}; do
+
+            #Attempts to define new paths and/or images based upon VM names:
+            new_path=(${path//$src_vm/$dest_vm})
+
+            if [[ $path != $new_path ]]; then
+
+            # When $path results modified by matches in VM name, asks for confirmation:
+            read -p "Create/Define automatically disk image path as '$new_path'? [ENTER to confirm, or insert a custom path manually]: " choice
+
+            while true; do
+
+                if [ -z $choice ]; then
+
+                    # User confirms the automatic choice:
+                    dest_img_paths_list+=($new_path)
+                    break
+
+                elif [[ $choice == /* ]]; then
+
+                    # User defined the path manually:
+                    dest_img_paths_list+=($choice)
+                    break
+                else
+                    read -p "$choice : Invalid choice. Insert an absolute path to the new disk image, or press ENTER to set it as '$new_path': " choice
+                fi
+            done
+
+            else
+
+                echo "Disk image '$path' cannot be modified automatically by this script. Choose one of the following options:"
+                echo ""
+                echo "1. Insert manually the path to the new disk image"
+                echo "2. Keep using the same disk image in both VMs: '$src_vm' and '$dest_vm' (may cause issues, use at your own risk)"
+                echo "3. Do not define this  "
+                read -p " What would you like to do?" choice
+
+
+
+
+                # Replaces matching path for a new path:
+                sed -i -e "s|<source file='$path'/>|<source file='${dest_img_paths_list[$i]}'/>|" $vm_definitions_file
+
+                # Creates the folder that will contain the given disk image:
+                mkdir -p $(dirname $new_path)
+            else
+                echo "WARNING: Could not find a match to replace path '$path' in VM '$dest_vm'. You will need to replace"
+                # No matches for $src_vm were found:
+                failed_paths_list+=($path)
+            fi
+            ((i++))
+        done
+
+        if [ ! -z ${dest_img_paths_list[@]} ]; then
+
+            # $src_vm disks must be closed in order to perform a copy:
+            if [[ $copy_disks ]] && [[ $(domain_state $src_vm) == running ]]; then
+
+                # Mark $src_vm  to be turned on after the copy:
+                src_vm_was_on=1
+
+                # Shuts down $src_vm
+                shutdown_vm $src_vm
+
+                # Gets the status of the operation:
+                shutdown_status=$?
+            fi
+
+            i=0
+            for image_path in ${dest_img_paths_list[@]}; do
+
+                # Creates the full path for each image file, if doesn't exist:
+                mkdir -p $(dirname $image_path)
+
+                if [ $copy_disks ] && [[ $shutdown_status -eq 0 ]]; then
+
+                    # Copies the image disk only when conditions apply:
+                    echo "INFO: Replicating '${src_img_paths_list[$i]}' as '$image_path'..."
+                    qemu-img convert -O qcow2 ${src_img_paths_list[$i]} $image_path
+                fi
+                ((i++))
+            done
+
+            # Starts $src_vm if it was previously running before the copy:
+            [[ $src_vm_was_on ]] && virsh start $src_vm
+        fi
+
+        # Reports about the success/fail of the operation:
+        # -----------------------------------------------------------------------------
+
 # -----------------------------------------------------------------------------
 
-    # Self-generated UUID to replace the original one
-    vm_uuid=$(uuidgen)
-
-
-    # Path to xml definitions file to be processed:
-    vm_xml_path=$working_path/$vm_name.xml
-
-    # Dumps current VMs XML file to a temporal location:
-    virsh dumpxml --inactive --security-info $source_vm > $vm_xml_path
-
-    # Changes its name internally
-
-# -----------------------------------------------------------------------------
+    else
+        echo "ERROR: No persistent Virtual Machines detected! (is libvirt service running?)"
+    fi
+else
+    # Argument(s) detected. By now, only shows the help and exits:
+    echo "WARNING: Arguments aren't suported"
+    #show_help
+    #status=0
+fi
 
 exit $status
