Added 'create_backup_chain' function

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -249,6 +249,46 @@ domains_list()
 }
 
 ###############################################################################
+# Virtnbdbackup Related Functions:
+###############################################################################
+
+#------------------------------------------------------------------------------
+# Creates a backup chain of given domain ($1) on $BACKUP_MAIN_PATH with given options
+#------------------------------------------------------------------------------
+create_backup_chain()
+{
+
+    local domain=$1
+    local domain_backup_path=$BACKUP_MAIN_PATH/$domain
+
+    # Backup Mode:
+    local backup_mode="full"
+
+    # Extra options passed to virtnbdbackup:
+    local options
+    [[ -z  $NO_BACKUP_COMPRESSION ]] && options=" --compress"
+
+    # Notifies the user about the ongoing process:
+    echo "INFO: Starting a $backup_mode backup of $domain (this may take some time, or even look freezed...)"
+
+    # Executes the operation:
+    virtnbdbackup -d $domain -l $backup_mode -o $domain_backup_path $options
+    local create_backup_chain_status=$?
+
+    if [[ $create_backup_chain_status -eq 0 ]]; then
+
+        echo "INFO: $backup_mode backup of $domain successfully finished!"
+    else
+
+        echo "ERROR: virtnbdbackup exited with status $status. Read the logs above to determine the problem"
+
+    fi
+
+    return $create_backup_chain_status
+
+}
+
+###############################################################################
 # POSIX Related Functions:
 ###############################################################################
 
