Changed user variables / sorting by name

diff --git a/scripts/update_backup_chain b/scripts/update_backup_chain
--- a/scripts/update_backup_chain
+++ b/scripts/update_backup_chain
@@ -65,7 +65,7 @@ if [[ $ONGOING_BACKUP == false ]]; then
                 if [[ $(domain_state $domain) == running ]]; then
 
                     # Only when VM is running, attempts to perform an incremental backup:
-                    do_backup_chain $domain "inc" $BACKUPS_MAIN_PATH $VIRTNBDBACKUP_ARGS
+                    do_backup_chain $domain "inc" $LOCAL_BACKUP_PATH $VIRTNBDBACKUP_ARGS
                     echo ""
 
                     if [[ $? -eq 0 ]]; then
@@ -99,15 +99,15 @@ if [[ $ONGOING_BACKUP == false ]]; then
                         fi
                     fi
 
-                    if [[ ${backup_chain_success[$i]} == $domain ]] && [[ ! -z $REMOTE_BACKUPS_MAIN_PATH ]]; then
+                    if [[ ${backup_chain_success[$i]} == $domain ]] && [[ ! -z $RSYNC_BACKUP_PATH ]]; then
 
                         # Incremental backup was successful and remote endpoint is (correctly) set,
                         # attempts to transfer changes via rsync:
 
                         echo "$domain: Syncing changes to remote endpoint..."
 
-                        # Transfer backup using SSH_OPTS and RSYNC_ARGS:
-                        rsync $RSYNC_ARGS -e "ssh $SSH_OPTS" $BACKUPS_MAIN_PATH/$domain/ $REMOTE_BACKUPS_MAIN_PATH/$domain/
+                        # Transfer backup using SSH_OPTIONS and RSYNC_ARGS:
+                        rsync $RSYNC_ARGS -e "ssh $SSH_OPTIONS" $LOCAL_BACKUP_PATH/$domain/ $RSYNC_BACKUP_PATH/$domain/
 
                         # Depending on success with rsync, will add the VM to $remote_success or $remote_fail
                         if [[ $? -eq 0 ]]; then
@@ -131,10 +131,10 @@ if [[ $ONGOING_BACKUP == false ]]; then
 
                 else
                     # VM is presumably shut off. Will attempts to start it:
-                    if [[ ! -z $RAM_LIMIT_PER_SCHED_BACKUP ]]; then
+                    if [[ ! -z $VM_RAM_LIMIT ]]; then
 
                         # And needs to check how much memory uses by default, throttling it if limits are established:
-                        if [[ $(domain_getmem $domain --max) -gt $RAM_LIMIT_PER_SCHED_BACKUP ]]; then
+                        if [[ $(domain_getmem $domain --max) -gt $VM_RAM_LIMIT ]]; then
 
                             # If max value is greater than the established limit, sets the VM RAM temporarily to such limit:
                             memlimit_active="yes"
@@ -143,11 +143,11 @@ if [[ $ONGOING_BACKUP == false ]]; then
                             original_ram_size=$(domain_getmem $domain)
 
                             # Applies temporal values (according user input, but values are grabbed from virsh in KiB):
-                            domain_setmem "$domain" "$RAM_LIMIT_PER_SCHED_BACKUP"
+                            domain_setmem "$domain" "$VM_RAM_LIMIT"
 
                             [[ $? -eq 0 ]] \
-                                && echo "$domain: RAM size temporarily throttled from ${original_ram_size// / \/ } to $RAM_LIMIT_PER_SCHED_BACKUP KiB for this task" \
-                                || echo "WARNING: Failed to set $domain RAM size to user defined limit of $RAM_LIMIT_PER_SCHED_BACKUP KiB"
+                                && echo "$domain: RAM size temporarily throttled from ${original_ram_size// / \/ } to $VM_RAM_LIMIT KiB for this task" \
+                                || echo "WARNING: Failed to set $domain RAM size to user defined limit of $VM_RAM_LIMIT KiB"
                         fi
                     fi
 
@@ -212,7 +212,7 @@ if [[ $ONGOING_BACKUP == false ]]; then
         echo "Failed Backups:     ${backup_chain_failed[@]:-"None"}"
         echo "Misbehaving VMs:    ${domain_poweron_failed[@]:-"None"}"
 
-        if [[ ! -z $REMOTE_BACKUPS_MAIN_PATH ]]; then
+        if [[ ! -z $RSYNC_BACKUP_PATH ]]; then
 
             # Only show remote stats when remote endppoint is set:
             echo ""
