Added warning if fails to revert original RAM settings

diff --git a/scripts/vm-babysitter b/scripts/vm-babysitter
--- a/scripts/vm-babysitter
+++ b/scripts/vm-babysitter
@@ -603,7 +603,10 @@ create_backup_chain()
 
                         # RAM was previously throttled. Reverting to its original values:
                         domain_setmem $domain $original_ram_size
-                        echo "$domain: Reverted RAM size to its original setting of ${original_ram_size// / \/ } KiB"
+
+                        [[ $? -eq 0 ]] \
+                        && echo "$domain: Reverted RAM size to its original setting of ${original_ram_size// / \/ } KiB" \
+                        || echo "WARNING: Failed to revert $domain RAM size to its original setting!"
                     fi
                 fi
 
