Renamed some variables for more clarity

diff --git a/scripts/vm-backup b/scripts/vm-backup
--- a/scripts/vm-backup
+++ b/scripts/vm-backup
@@ -139,9 +139,9 @@ if [[ -n ${backups_list[@]} ]]; then
             virtnbdbackup $start_domain -d $domain -l $backup_mode -o $LOCAL_BACKUP_PATH/$domain $VIRTNBDBACKUP_ARGS
 
             # Get last status for virtnbdbackup:
-            virtnbdbackup_status=$?
+            virtnbdbackup_exit_code=$?
 
-            if [[ $virtnbdbackup_status -eq 0 ]]; then
+            if [[ $virtnbdbackup_exit_code -eq 0 ]]; then
 
                 # Backup chain creation was successful!
                 backup_success_list+=($domain)
@@ -151,7 +151,7 @@ if [[ -n ${backups_list[@]} ]]; then
                 # Failed to create a new backup chain:
                 backup_failed_list+=($domain)
 
-                echo "WARNING: $domain: $backup_mode backup failed (status $virtnbdbackup_status)"
+                echo "WARNING: $domain: $backup_mode backup failed (status $virtnbdbackup_exit_code)"
             fi
 
         else
@@ -172,9 +172,9 @@ if [[ -n ${backups_list[@]} ]]; then
             vm-rsync $domain
 
             # Get last status for rsync:
-            rsync_status=$?
+            rsync_exit_code=$?
 
-            if [[ $rsync_status -eq 0 ]]; then
+            if [[ $rsync_exit_code -eq 0 ]]; then
 
                 # Rsync exited normally:
                 rsync_success_list+=($domain)
diff --git a/scripts/vm-rsync b/scripts/vm-rsync
--- a/scripts/vm-rsync
+++ b/scripts/vm-rsync
@@ -44,7 +44,7 @@ if [[ -n ${rsync_list[@]} ]]; then
     for domain in ${rsync_list[@]}; do
 
         # (Re)Initialize status variable:
-        rsync_backup_status=""
+        rsync_exit_code=""
 
         # Build rsync_source directly from variables:
         rsync_source=$LOCAL_BACKUP_PATH/$domain
@@ -66,24 +66,24 @@ if [[ -n ${rsync_list[@]} ]]; then
                 rsync $RSYNC_ARGS -e "ssh $SSH_OPTIONS" $rsync_source/ $rsync_destination/
 
                 # Get last status for rsync:
-                rsync_backup_status=$?
+                rsync_exit_code=$?
             else
 
                 # Locally reachable endpoint. Run rsync with user defined arguments only:
                 rsync $RSYNC_ARGS $rsync_source/ $rsync_destination/
 
                 # Get last status for rsync:
-                rsync_backup_status=$?
+                rsync_exit_code=$?
             fi
 
-            if [[ $rsync_backup_status -eq 0 ]]; then
+            if [[ $rsync_exit_code -eq 0 ]]; then
 
                 rsync_success+=($domain)
                 echo "$domain: Backup chain synced successfully"
 
             else
                 rsync_failed+=($domain)
-                echo "$domain: Failed to sync backup chain to $rsync_destination (rsync status $rsync_backup_status)"
+                echo "$domain: Failed to sync backup chain to $rsync_destination (rsync status $rsync_exit_code)"
             fi
         else
             rsync_skipped+=($domain)
@@ -107,7 +107,7 @@ case $rsync_action in
         elif [[ ${#rsync_list[@]} -eq 1 && -z ${rsync_skipped[@]} ]]; then
 
             # Only exits with rsync code when there was only one backup on the list and existed (not skipped):
-            exit $rsync_backup_status
+            exit $rsync_exit_code
         fi
     ;;
 
