Fixed errors and improved procedure of backup chains archiving and its retention policy

diff --git a/scripts/vm-functions b/scripts/vm-functions
--- a/scripts/vm-functions
+++ b/scripts/vm-functions
@@ -493,8 +493,9 @@ do_backup_chain()
 ###############################################################################
 
 # -----------------------------------------------------------------------------
-# Renames passed backup folder with a timestamp. If $2 is passed, deletes older
-# backups, except the most recent ones according with timestamp on such folder names:
+# Renames a backup folder (backup_path/domain) given as first argument
+# Second argument, when passed, is the max # of old backup chains with same timestamp,
+# and implies retention policy:
 # -----------------------------------------------------------------------------
 archive_backup()
 {
@@ -504,49 +505,41 @@ archive_backup()
     # VM name basename:
     local domain=$(basename $1)
 
-    # When integer is passed as second argument, takes it as the max # of backup chains to keep locally:
-    [[ ! -z $2 ]] && [[ $2 =~ [0-9] ]] && local backups_to_keep=$2
-
-    # And if second argument is OK, take the third as timestamp to be used to rename old backup:
-    #[[ ! -z $backups_to_keep ]] && local timestamp=$3
-
     # Generate an updated time stamp to rename archived backups:
     local timestamp=$(date '+%Y-%m-%d.%H:%M:%S')
 
-    if [[ $backups_to_keep != 0 ]]; then
+    # Archives the current backup chain, by renaming it with time stamp:
+    mv $backup_path/$domain $backup_path/$domain.$timestamp
+    echo "$domain: Current backup chain archived as $backup_path/$domain.$timestamp"
 
-        # Archives the current backup chain, by renaming it with time stamp:
-        mv $backup_path/$domain $backup_path/$domain.$timestamp
+    if [[ ! -z $2 ]]; then
 
-        echo "$domain: Current backup chain archived as $backup_path/$domain.$timestamp"
+    # Second argument, when passed, triggers retention policy,
+    # preserving as many old backup chains as the integer value is:
+    local backups_to_keep=$2
+    echo "Applying local retention policy..."
 
-        if [[ $backups_to_keep -ge 1 ]]; then
+    # Position of the first folder to delete, ordered from most recent timestamp:
+    local index=$( expr $backups_to_keep + 1 )
 
-            # And when is greater than zero, deletes older backup chains, except the last ones as defined in the same variable:
+    # Creates a list with EXACT match of archived folder(s) to delete.
+    # Pattern is based upon $(date '+%Y-%m-%d.%H:%M:%S'):
+    local old_backups_list=($(find $backup_path -type d -name "$domain.*" | sort -r | grep -E "^$backup_path/$domain.[0-9]{4}-[0-9]{2}-[0-9]{2}.[0-9]{2}:[0-9]{2}:[0-9]{2}$" | tail -n +$index))
 
-            # Position of the first folder to delete, ordered from most recent timestamp
-            local index=$( expr $backups_to_keep + 1 )
+        if [[ ! -z ${old_backups_list[@]} ]]; then
 
-            # Creates a list with exact match of archived folders to delete (manually archived backup chains without this match aren't touched). Pattern is based upon $(date '+%Y-%m-%d.%H:%M:%S'):
-            local old_backups_list=($(find $backup_path -type d -name "$domain.*" | sort -r | grep -E "^$domain.[0-9]{4}-[0-9]{2}-[0-9]{2}.[0-9]{2}:[0-9]{2}:[0-9]{2}$" | tail -n +$index))
-
-            if [[ ! -z ${old_backups_list[@]} ]]; then
-
-                # Deletes all folders in the above generated list:
-                rm -rf ${old_backups_list[@]}
-                echo "$domain: ${#old_backups_list[@]} archived backup chain(s) found and deleted"
-            fi
+            # Deletes all folders in the above generated list:
+            echo "$domain: Deleting ${#old_backups_list[@]} old backup chain(s)..."
+            rm -rfv ${old_backups_list[@]}
+        else
+            echo "$domain: No old backup chains to delete by now"
         fi
-    else
-
-        # When zero, remove backup chain directly:
-        rm -rf $backup_path/$domain
-        echo "$domain: Current backup chain deleted"
     fi
 }
 
 # -----------------------------------------------------------------------------
 # Similar with 'archive_backup' but operates on a remote endpoint via SSH:
+# Returns SSH error status if fails attempt to connect:
 # -----------------------------------------------------------------------------
 archive_remote_backup()
 {
@@ -562,54 +555,60 @@ archive_remote_backup()
     # VM name basename:
     local domain=$(basename $remote_backup_path)
 
-    # When passed as second argument, takes it as the max # of backup chains to keep remotely:
-    [[ ! -z $2 ]] && [[ $2 =~ [0-9] ]] && local remote_backups_to_keep=$2
+    # Attempts to comunicate with the remote host:
+    ssh $SSH_OPTIONS $remote_server "exit 0"
+    local remote_server_status=$?
 
-    # And if second argument is OK, take the third as timestamp to be used to rename old backup:
-    #[[ ! -z $backups_to_keep ]] && local timestamp=$3
+    if [[ $remote_server_status -eq 0 ]]; then
 
-    # Generate an updated time stamp to rename archived backups:
-    local timestamp=$(date '+%Y-%m-%d.%H:%M:%S')
+        # Remote Server is reachable.
 
-    # Checks in advance is remote backup path exists or not:
-    local remote_backup_chain_exists=$(ssh $SSH_OPTIONS $remote_server "[[ -d $remote_backup_path ]] && echo \"yes\" || echo \"no\"")
+        # Generate an updated time stamp to rename archived backups:
+        local timestamp=$(date '+%Y-%m-%d.%H:%M:%S')
 
-    if [[ $remote_backup_chain_exists == "yes" ]]; then
+        # Checks in advance if remote backup path exists or not:
+        local remote_backup_chain_exists=$(ssh $SSH_OPTIONS $remote_server "[[ -d $remote_backup_path ]] && echo \"yes\" || echo \"no\"")
 
-        # Previously active backup chain was found on remote endpoint:
-        case $remote_backups_to_keep in
+        if [[ $remote_backup_chain_exists == "yes" ]]; then
 
-            0)
-                # When zero, do not archive. Remove backup chain directly:
-                ssh $SSH_OPTIONS $remote_server "rm -rf $remote_backup_path"
-                echo "$domain: Current backup chain at $remote_server deleted"
-            ;;
+            # Archive remote backup chain:
+            ssh $SSH_OPTIONS $remote_server "mv $remote_backup_path $remote_backup_path.$timestamp"
+            echo "$domain: Current backup chain at $remote_server renamed as $remote_backup_path.$timestamp"
 
-            *)
-                # When not zero (natural integer or null expected, archive backup chain:
-                ssh $SSH_OPTIONS $remote_server "mv $remote_backup_path $remote_backup_path.$timestamp"
-                echo "$domain: Current backup chain at $remote_server renamed as $remote_backup_path.$timestamp"
-            ;;
-        esac
-    fi
 
-    if [[ $remote_backups_to_keep -ge 1 ]]; then
+        elif [[ $remote_backup_chain_exists == "no" ]]; then
 
-        # Independently of any active backup chain found above, if retention policy is >=1, deletes found archived backup chains except the last ones as defined in the same variable:
-
-        # Position of the first folder to delete, ordered from most recent timestamp
-        local index=$( expr $remote_backups_to_keep + 1 )
-
-        # Creates a list with exact match of archived folders to delete (manually archived backup chains without this match aren't touched). Pattern is based upon $(date '+%Y-%m-%d.%H:%M:%S'):
-        local remote_old_backups_list=($(ssh $SSH_OPTIONS $remote_server "find $remote_main_backup_path -type d -name \"$domain.*\" | sort -r | grep -E \"^$domain.[0-9]{4}-[0-9]{2}-[0-9]{2}.[0-9]{2}:[0-9]{2}:[0-9]{2}$\" | tail -n +$index"))
-
-        if [[ ! -z ${remote_old_backups_list[@]} ]]; then
-
-            # Deletes all folders in the above generated list:
-            ssh $SSH_OPTIONS $remote_server "rm -rf ${remote_old_backups_list[@]}"
-
-            echo "$domain: ${#remote_old_backups_list[@]} archived backup chain(s) found and deleted at $remote_server"
+            echo "$domain: No current backup chain(s) found at $remote_server"
         fi
+
+        if [[ ! -z $2 ]]; then
+
+            # When a second argument is passed, takes it as the max # of backup chains to keep remotely:
+            local remote_backups_to_keep=$2
+            echo "Applying remote retention policy on $remote_server..."
+
+            # Position of the first folder to delete, ordered from most recent timestamp
+            local index=$( expr $remote_backups_to_keep + 1 )
+
+            # Creates a list with EXACT match of archived folder(s) to delete.
+            # Pattern is based upon $(date '+%Y-%m-%d.%H:%M:%S'):
+            local remote_old_backups_list=($(ssh $SSH_OPTIONS $remote_server "find $remote_main_backup_path -type d -name \"$domain.*\" | sort -r | grep -E \"^$remote_main_backup_path/$domain.[0-9]{4}-[0-9]{2}-[0-9]{2}.[0-9]{2}:[0-9]{2}:[0-9]{2}$\" | tail -n +$index"))
+
+            if [[ ! -z ${remote_old_backups_list[@]} ]]; then
+
+                # Deletes all folders in the above generated list:
+                ssh $SSH_OPTIONS $remote_server "rm -rfv ${remote_old_backups_list[@]}"
+                echo "$domain: Deleting ${#remote_old_backups_list[@]} old backup chain(s)..."
+
+            else
+                echo "$domain: No old backup chains to delete by now"
+            fi
+        fi
+    else
+
+        # Returns status of failed connection:
+        echo "WARNING: Remote endpoint $remote_server is currently unreachable (status: $remote_server_status)"
+        return $remote_server_status
     fi
 }
 
