disk_image_delete_bitmap: Improved messages and extended status

diff --git a/scripts/vm-functions b/scripts/vm-functions
--- a/scripts/vm-functions
+++ b/scripts/vm-functions
@@ -682,12 +682,14 @@ disk_image_bitmap_list()
 }
 
 # -----------------------------------------------------------------------------
-# Deletes specific bitmaps of a given virtual disk, or all if '--all' argument is passed instead:
+# Deletes specific bitmaps of a given virtual disk, or all if '--all' argument is passed instead.
+# Returns '0' if ended successfully, '1' if ended with errors, '2' if success but power cycle is required and '256' if no bitmaps were found:
 # -----------------------------------------------------------------------------
 disk_image_delete_bitmap()
 {
 
     local bitmaps_list
+    local delete_bitmap_status
 
     # First argument is always the full path to the disk image:
     local virtual_disk_path=$1
@@ -718,14 +720,32 @@ disk_image_delete_bitmap()
         echo "$domain: Removing ${#bitmaps_list[@]} bitmap(s)..."
 
         for bitmap in ${bitmaps_list[@]}; do
-            &> /dev/null qemu-img bitmap --remove $virtual_disk_path $bitmap
+
+            qemu-img bitmap --remove $virtual_disk_path $bitmap
+
+            if [[ $? -ne 0 ]]; then
+
+                # When a bitmap can't be deleted by any reason, operation is cancelled:
+                delete_bitmap_status=1
+                echo "ERROR: Issues found in $(basename $virtual_disk_path) when deleting bitmap '$bitmap' (operation has been cancelled)"
+                break
+            fi
         done
 
-        [[ $(domain_state $domain) != "shut off" ]] && echo "$(basename $virtual_disk_path): VM full power cycle is needed in order to apply changes"
+        if [[ -z $delete_bitmap_status ]]; then
+
+            # Ended successfully. When domain is not shut down, status is 2 and makes notice about mame
+            [[ $(domain_state $domain) == "shut off" ]] && delete_bitmap_status=0 || { delete_bitmap_status=2; local bitmap_message="(a full power cycle is required)"; }
+
+            echo "$(basename $virtual_disk_path): Success $bitmap_message"
+        fi
 
     else
+        delete_bitmap_status=256
         echo "$(basename $virtual_disk_path): No bitmaps to delete"
     fi
+
+    return $delete_bitmap_status
 }
 
 # -----------------------------------------------------------------------------
